// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: nodes.sql

package db

import (
	"context"
)

const createNode = `-- name: CreateNode :one
INSERT INTO nodes (name, address, public_host, domain, cert_sha256, enabled, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, 1, ?, ?)
RETURNING id, name, address, public_host, domain, cert_sha256, enabled, created_at, updated_at
`

type CreateNodeParams struct {
	Name       string
	Address    string
	PublicHost string
	Domain     string
	CertSha256 string
	CreatedAt  int64
	UpdatedAt  int64
}

func (q *Queries) CreateNode(ctx context.Context, arg CreateNodeParams) (Node, error) {
	row := q.db.QueryRowContext(ctx, createNode,
		arg.Name,
		arg.Address,
		arg.PublicHost,
		arg.Domain,
		arg.CertSha256,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Node
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Address,
		&i.PublicHost,
		&i.Domain,
		&i.CertSha256,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteNode = `-- name: DeleteNode :exec
DELETE FROM nodes WHERE id = ? AND id != 1
`

func (q *Queries) DeleteNode(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteNode, id)
	return err
}

const getNode = `-- name: GetNode :one
SELECT id, name, address, public_host, domain, cert_sha256, enabled, created_at, updated_at FROM nodes WHERE id = ?
`

func (q *Queries) GetNode(ctx context.Context, id int64) (Node, error) {
	row := q.db.QueryRowContext(ctx, getNode, id)
	var i Node
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Address,
		&i.PublicHost,
		&i.Domain,
		&i.CertSha256,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listNodes = `-- name: ListNodes :many
SELECT id, name, address, public_host, domain, cert_sha256, enabled, created_at, updated_at FROM nodes ORDER BY id
`

func (q *Queries) ListNodes(ctx context.Context) ([]Node, error) {
	rows, err := q.db.QueryContext(ctx, listNodes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Node{}
	for rows.Next() {
		var i Node
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Address,
			&i.PublicHost,
			&i.Domain,
			&i.CertSha256,
			&i.Enabled,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setNodeCert = `-- name: SetNodeCert :exec
UPDATE nodes SET cert_sha256 = ?, updated_at = ? WHERE id = ?
`

type SetNodeCertParams struct {
	CertSha256 string
	UpdatedAt  int64
	ID         int64
}

func (q *Queries) SetNodeCert(ctx context.Context, arg SetNodeCertParams) error {
	_, err := q.db.ExecContext(ctx, setNodeCert, arg.CertSha256, arg.UpdatedAt, arg.ID)
	return err
}

const updateNode = `-- name: UpdateNode :one
UPDATE nodes SET name = ?, address = ?, public_host = ?, domain = ?, enabled = ?, updated_at = ? WHERE id = ? RETURNING id, name, address, public_host, domain, cert_sha256, enabled, created_at, updated_at
`

type UpdateNodeParams struct {
	Name       string
	Address    string
	PublicHost string
	Domain     string
	Enabled    int64
	UpdatedAt  int64
	ID         int64
}

func (q *Queries) UpdateNode(ctx context.Context, arg UpdateNodeParams) (Node, error) {
	row := q.db.QueryRowContext(ctx, updateNode,
		arg.Name,
		arg.Address,
		arg.PublicHost,
		arg.Domain,
		arg.Enabled,
		arg.UpdatedAt,
		arg.ID,
	)
	var i Node
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Address,
		&i.PublicHost,
		&i.Domain,
		&i.CertSha256,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
